### ISSUE TITLE
Add support for additional fields

### ISSUE THREAD

**Issue by coltenkrauter** [masci/drone-datadog#4]
Would you add support for some additional fields for the POST to the DataDog events endpoint? For example, I would like to supply a `url` which would link, in my case, to the Drone build.

[DataDog events](https://docs.datadoghq.com/api/latest/events/)

**Comment by masci** [comment]
Hi @coltenkrauter thanks for reporting!

I've added all the available fields in https://github.com/masci/drone-datadog/commit/1a797c0d547737aa93e0c5a9855ba6db960aa49e, can you try out `masci/drone-datadog:unstable` and let me know if that works for you? In case, I'll make a new release with the changes from `master`.

**Comment by masci** [comment]
Fixed in [v.0.3.0](https://github.com/masci/drone-datadog/releases/tag/v0.3.0)
